### ISSUE TITLE
Analyse des différences de codes Fantoir recalculés et DGFIP

### ISSUE THREAD

**Issue by mmortier** [etalab/fantoir#17]
Besoin d'analyse des codes fantoir retrouvés par ban-plateforme au moment du compose. 
Utilise ce dépôt de code. 
Des différences sont trouvées entre les codes Fantoir de la DGFIP et les codes retrouvés. 
Analyse sur le département 80.
Malgré une correspondance de 80 %, des codes fantoir annulés ressortent dans la BAN.

```[tasklist]
### 
- [ ] https://github.com/BaseAdresseNationale/fantoir/issues/22
- [ ] https://github.com/BaseAdresseNationale/fantoir/issues/23
```

**Comment by jdesboeufs** [comment]
Je vous pointe ceci : https://github.com/BaseAdresseNationale/fantoir/blob/master/lib/index.js#L50

**Comment by mmortier** [comment]
Suite à la correction (non encore déployée à ce jour) il reste des exemples où la BAN récupère des codes de voies annulées. 
Quelques exemples à investiguer : 
dans le département 57  :
    - commune 57260 Rue Maurice de Tastes, RIVOLI 0272 annulée le 06/07/1995
    - commune 57724 Square Michel Nicoletta, RIVOLI B065 annulée le 14/05/1997
Exemple dans le département 80  :
    - commune 57137 Grande Rue, RIVOLI 0200 annulée le 30/05/1988
